CREATE TABLE venditori
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ragione_sociale VARCHAR(60),
    partita_iva CHAR(11) UNIQUE
);

CREATE TABLE clienti
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60),
    cognome VARCHAR(60),
    codice_fiscale CHAR(16) UNIQUE 
);

CREATE TABLE accounts
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32),
    password VARCHAR(32),
    cliente_id INTEGER UNIQUE,
    FOREIGN KEY (cliente_id) REFERENCES clienti(id),
    venditore_id INTEGER UNIQUE,
    FOREIGN KEY(venditore_id) REFERENCES venditori(id)
);

CREATE TABLE stampanti_in_vendita 
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(32),
    modello VARCHAR(32),
    url_immagine VARCHAR(512),
    tipo_stampa VARCHAR(32),
    gamma_colori VARCHAR(32),
    descrizione VARCHAR(4096),
    prezzo_unitario DOUBLE PRECISION,
    quantita INTEGER,
    venditore_id INTEGER,
    FOREIGN KEY(venditore_id) REFERENCES venditori(id)
);

CREATE TABLE altre_caratteristiche_stampante
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caratteristica VARCHAR(64)
);

CREATE TABLE stampanti_altreCaratteristiche
(
    stampanti_in_vendita_id INTEGER,
    altre_caratteristiche_stampante_id INTEGER,
    FOREIGN KEY (stampanti_in_vendita_id) REFERENCES stampanti_in_vendita(id),
    FOREIGN KEY(altre_caratteristiche_stampante_id) REFERENCES altre_caratteristiche_stampante(id),
    PRIMARY KEY (stampanti_in_vendita_id,altre_caratteristiche_stampante_id)
);

CREATE TABLE conti_corrente
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER UNIQUE,
    codice_accesso INTEGER,
    importo_movimento DOUBLE PRECISION,
    cliente_id INTEGER UNIQUE,
    FOREIGN KEY (cliente_id) REFERENCES clienti(id),
    venditore_id INTEGER UNIQUE,
    FOREIGN KEY(venditore_id) REFERENCES venditori(id)
);

INSERT INTO venditori (id, ragione_sociale, partita_iva)
VALUES (default, 'StampantiSrl', '01234567890');

INSERT INTO accounts (username, password, venditore_id )
VALUES ('stampantisrl','ggghhh',1);

INSERT INTO conti_corrente (id, numero, codice_accesso, importo_movimento, venditore_id)
VALUES (default, 2001, 1212, 4000, 1);

INSERT INTO clienti(id, nome, cognome, codice_fiscale)
VALUES
    (default, 'Mario', 'Bianchi', 'BNCMRA81A01A100A'),
    (default, 'Franco', 'Milani', 'MLNFRN82A02A200B'),
    (default, 'Veronica', 'Marini', 'MRNVRN83A03A300C');

INSERT INTO accounts (id, username, password, cliente_id )
VALUES
    (default, 'MarioBianchi','aaabbb',1),
    (default, 'FrancoMilani','cccddd',2),
    (default, 'VeronicaMarini', 'eeefff', 3);

INSERT INTO conti_corrente (id, numero, codice_accesso, importo_movimento, cliente_id)
VALUES 
    (default, 1001, 1111, 1100, 1),
    (default, 1002, 2222, 1200, 2),
    (default, 1003, 3333, 1300, 3);

INSERT INTO altre_caratteristiche_stampante (id, caratteristica)
VALUES 
    (default, 'multifunzione'),
    (default, 'wireless'),
    (default, 'A3'),
    (default, 'fronte-retro automatico');

