CREATE TABLE accounts
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32),
    password VARCHAR(32)
);

CREATE TABLE venditori
(
    account_id INTEGER,
    PRIMARY KEY (account_id),
    FOREIGN KEY (account_id) REFERENCES accounts(id),
    ragione_sociale VARCHAR(60),
    partita_iva CHAR(11) UNIQUE
);

CREATE TABLE clienti
(
    account_id INTEGER,
    PRIMARY KEY (account_id),
    FOREIGN KEY (account_id) REFERENCES accounts(id),
    nome VARCHAR(60),
    cognome VARCHAR(60),
    codice_fiscale CHAR(16) UNIQUE 
);

CREATE TABLE stampanti_in_vendita 
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(32),
    modello VARCHAR(32),
    url_immagine VARCHAR(512),
    tipo_stampa VARCHAR(32),
    gamma_colori VARCHAR(32),
    descrizione VARCHAR(4096),
    prezzo_unitario DOUBLE PRECISION,
    quantita INTEGER,
    venditore_id INTEGER,
    FOREIGN KEY(venditore_id) REFERENCES venditori(account_id)
);

CREATE TABLE altre_caratteristiche_stampante
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caratteristica VARCHAR(64)
);

CREATE TABLE stampanti_altreCaratteristiche
(
    stampanti_in_vendita_id INTEGER,
    altre_caratteristiche_stampante_id INTEGER,
    FOREIGN KEY (stampanti_in_vendita_id) REFERENCES stampanti_in_vendita(id),
    FOREIGN KEY(altre_caratteristiche_stampante_id) REFERENCES altre_caratteristiche_stampante(id),
    PRIMARY KEY (stampanti_in_vendita_id,altre_caratteristiche_stampante_id)
);

CREATE TABLE conti_corrente
(
    account_id INTEGER,
    PRIMARY KEY (account_id),
    FOREIGN KEY (account_id) REFERENCES accounts(id),
    numero INTEGER UNIQUE,
    codice_accesso INTEGER,
    saldo DOUBLE PRECISION
);

INSERT INTO accounts(id, username, password )
VALUES
    (default, 'MarioBianchi','aaabbb'),
    (default, 'FrancoMilani','cccddd'),
    (default, 'VeronicaMarini', 'eeefff');

INSERT INTO clienti(account_id, nome, cognome, codice_fiscale)
VALUES
    (1, 'Mario', 'Bianchi', 'BNCMRA81A01A100A'),
    (2, 'Franco', 'Milani', 'MLNFRN82A02A200B'),
    (3, 'Veronica', 'Marini', 'MRNVRN83A03A300C');

INSERT INTO accounts(id, username, password )
VALUES (default, 'stampantisrl','ggghhh');

INSERT INTO venditori(account_id, ragione_sociale, partita_iva)
VALUES (4, 'StampantiSrl', '01234567890');

INSERT INTO conti_corrente (account_id, numero, codice_accesso, saldo)
VALUES 
    (1, 1001, 1111, 1100),
    (2, 1002, 2222, 1200),
    (3, 1003, 3333, 1300),
    (4, 2001, 1212, 4000);

INSERT INTO stampanti_in_vendita(id, marca, modello, url_immagine, 
tipo_stampa, gamma_colori, descrizione, prezzo_unitario, quantita, venditore_id)
VALUES
    (default, 'Canon', 'iP8750', 'http://www.canon.it/Images/iP8750_Angle4_tcm80-1115696.jpg',
    'inkjet', 'a colori', 
    'Risoluzione di stampa: Fino a 9600 x 2400 dpi;
    Tecnologia di stampa:6 inchiostri separati (PGBK, BK, C, M, Y, GY) 
    Sistema con testina di stampa FINE con gocce d''inchiostro da 1 pl (min.)
    Inchiostri ChromaLife100+', 
    360, 20, 4),
    (default, 'Canon', 'i-SENSYS MF8550Cdn', 'http://www.canon.it/Images/i-Sensys-MF8550Cdn_Default_tcm80-1035436.jpg',
    'laser', 'a colori', 'nessuna', 420, 4, 4),
    (default, 'Epson', 'Ecotank ET-4550', 'https://www.epson.it/files/assets/converted/510m-310m/e/t/z/4/etz4550_med.png.png',
    'inkjet', 'inkjet', 'nessuna', 500, 15, 4),
    (default, 'Epson', 'workforce AL-MX200DNF', 'https://www.epson.it/files/assets/converted/510m-310m/a/l/g/m/algmx200dwf_noshadow.png.png',
    'laser', 'monocromatica', 'nessuna', 382, 20, 4),
    (default, 'Hp', 'Envy 7640', 'http://www.www8-hp.com/h22175/ItalyStore/Html/Merch/Images/c04385577_500x367.jpg',
    'inkjet', 'a colori', 'nessuna', 150, 45, 4),
    (default, 'Brother', 'HL-L6400DWT', 'http://www.brother.it/~/media/Product-Images/Devices/Printers/HL/HLL6400DWT/HLL6400DWT_main.ashx',
    'laser', 'monocromatica', 'nessuna', 1480, 2, 4);

INSERT INTO altre_caratteristiche_stampante(id, caratteristica)
VALUES 
    (default, 'multifunzione'),
    (default, 'wireless'),
    (default, 'A3'),
    (default, 'fronte-retro automatico');

INSERT INTO stampanti_altreCaratteristiche(stampanti_in_vendita_id, altre_caratteristiche_stampante_id)
VALUES 
    (1,2), (1,3),
    (2,1), (2,4),
    (3,1), (3,2), (3,4),
    (4,1), (4,2), (4,4),
    (5,1), (5,2), (5,4),
    (6,1), (6,2), (6,4);
